spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://mysqldb:3307/backend_db?useSSL=false
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto:  create
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
